apiVersion: v1
kind: ConfigMap
metadata:
  name: diary-config
  namespace: krypt
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgres"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  NEXT_PUBLIC_API_URL: "http://gateway:80"

---
apiVersion: v1
kind: Secret
metadata:
  name: diary-secrets
  namespace: krypt
type: Opaque
data:
  # Values are base64 encoded strings
  # 'postgres_password_1234' -> cG9zdGdyZXNfcGFzc3dvcmRfMTIzNA==
  # 'krypt_shared_jwt_secret_key_12345' -> a3J5cHRfc2hhcmVkX2p3dF9zZWNyZXRfa2V5XzEyMzQ1
  JWT_SECRET: a3J5cHRfc2hhcmVkX2p3dF9zZWNyZXRfa2V5XzEyMzQ1
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMyL3Bvc3RncmVzCg==
  POSTGRES_PASSWORD: cG9zdGdyZXMK
   
