apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: krypt
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: frontend-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: krypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: krypt-frontend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_API_GATEWAY_URL
              value: "" # Empty relative path routes locally to ingress domain
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: krypt-secrets
                  key: JWT_SECRET
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
