# ==============================================================================
# Ansible Inventory for Krypt Microservices
# ------------------------------------------------------------------------------
# Define your cloud hostnames or IP addresses below.
# Configure remote user, SSH key paths, and configuration variables.
# ==============================================================================

[krypt_servers]
# host1 ansible_host=34.201.55.123 ansible_user=ubuntu ansible_private_key_file=~/.ssh/krypt_aws.pem
# host2 ansible_host=54.12.222.12 ansible_user=ubuntu

[krypt_servers:vars]
# Shared variables for the server group
ansible_python_interpreter=/usr/bin/python3
